# Needed for keeping JDK 8
before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
dist: trusty
language: java
jdk:
  - openjdk8
script: mvn install -B -q
